version: 2.1

orbs:
  go: circleci/go@1.9.0

jobs:
  build-eotsd-stakercli:
    machine:
      image: ubuntu-2204:2024.01.1
    steps:
      - restore_cache:
          keys:
            - eotsd-ae30623a634450db81ce1755839754cc822bf5e5-stakercli-2fa54c9b0863b8d4a9c5e90ff74a25674dfeba8f-wasm
      - go/install:
          version: "1.21.4"
      - run:
          name: Build eotsd
          command: |
            if [ ! -f /home/circleci/.go_workspace/bin/eotsd ]; then
              git clone https://github.com/babylonchain/finality-provider.git
              cd finality-provider
              git checkout ae30623a634450db81ce1755839754cc822bf5e5
              mkdir -p /home/circleci/go/bin/
              make install
            fi
      - run:
          name: Build stakercli
          command: |
            if [ ! -f /home/circleci/.go_workspace/bin/stakercli ]; then
              git clone https://github.com/babylonchain/btc-staker.git
              cd btc-staker
              git checkout 2fa54c9b0863b8d4a9c5e90ff74a25674dfeba8f
              mkdir -p /home/circleci/go/bin/
              make install
            fi
      - run:
          name: download Wasm
          command: |
            if [ ! -f /home/circleci/.go_workspace/bin/stakercli ]; then
              sudo wget https://github.com/CosmWasm/wasmvm/releases/download/v1.5.2/libwasmvm.x86_64.so \
                -O /lib/libwasmvm.x86_64.so
            fi
      - save_cache:
          key: eotsd-ae30623a634450db81ce1755839754cc822bf5e5-stakercli-2fa54c9b0863b8d4a9c5e90ff74a25674dfeba8f-wasm
          paths:
            - /home/circleci/.go_workspace/bin/eotsd
            - /home/circleci/.go_workspace/bin/stakercli
            - /lib/libwasmvm.x86_64.so

  verify-offchain-tx:
    machine:
      image: ubuntu-2204:2024.01.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - eotsd-ae30623a634450db81ce1755839754cc822bf5e5-stakercli-2fa54c9b0863b8d4a9c5e90ff74a25674dfeba8f-wasm
      - run:
          name: Verify offchain signed transaction
          command: |
            export LD_LIBRARY_PATH=/lib/libwasmvm.x86_64.so:$LD_LIBRARY_PATH

            EOTSD_BIN=/home/circleci/.go_workspace/bin/eotsd \
            STAKERCLI_BIN=/home/circleci/.go_workspace/bin/stakercli \
            ./bbn-test-4/finality-providers/scripts/verify-new-fp-offchain.sh

  verify-onchain-BTC-tx:
    machine:
      image: ubuntu-2204:2024.01.1
    steps:
      - checkout
      - run:
          name: Verify onchain BTC transaction
          command: |
            ./bbn-test-4/finality-providers/scripts/verify-new-fp-onchain.sh

workflows:
  New-FP:
    jobs:
    - build-eotsd-stakercli
    - verify-onchain-BTC-tx
    - verify-offchain-tx:
        requires:
        - build-eotsd-stakercli
